apiVersion: v1
kind: PersistentVolume
metadata:
  name: akidb-pv
  labels:
    app: akidb
    type: local
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: akidb-storage
  hostPath:
    path: /mnt/data/akidb
    type: DirectoryOrCreate
