apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akidb-pvc
  namespace: akidb
  labels:
    app: akidb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: akidb-storage
