{{- if .Values.config.coldTier.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akidb.secretName" . }}
  labels:
    {{- include "akidb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.s3.accessKeyId }}
  access-key-id: {{ .Values.s3.accessKeyId | b64enc | quote }}
  {{- else }}
  access-key-id: ""
  {{- end }}
  {{- if .Values.s3.secretAccessKey }}
  secret-access-key: {{ .Values.s3.secretAccessKey | b64enc | quote }}
  {{- else }}
  secret-access-key: ""
  {{- end }}
  {{- if .Values.s3.sessionToken }}
  session-token: {{ .Values.s3.sessionToken | b64enc | quote }}
  {{- end }}
{{- end }}
